- name: "Launch octoprint server for flsun-q5-1, flsunq5-2, ender-cr-30"
  docker_container:
    name: "{{ item.name }}"
    image: octoprint/octoprint
    pull: true
    networks_cli_compatible: yes
    volumes: 
      - /srv/{{ item.name }}:/octoprint
    ports:
      - "{{ item.port }}:80"
    devices:
      - /dev/{{ item.ttyUSB }}
    restart_policy: always
    state: started
  with_items:
   - name: ender-cr30
     port: 8080
     ttyUSB: ttyUSB0
   - name: flsun-q5-1
     port: 8081
     ttyUSB: ttyUSB1
   - name: flsun-q5-2
     port: 8082
     ttyUSB: ttyUSB2
   - name: ender-6-1
     port: 8083
     ttyUSB: ttyUSB3